import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { 
  faHome, 
  faUser, 
  faCog, 
  faBuilding, 
  faFileContract, 
  faCreditCard, 
  faUsers, 
  faUserTie, 
  faUserShield, 
  faUserTag, 
  faReceipt, 
  faChartBar, 
  faChartLine, 
  faChartPie, 
  faTools, 
  faCalendarCheck, 
  faEnvelope, 
  faPercentage, 
  faFolder, 
  faPlusCircle, 
  faMoneyBillWave,
  faSignOutAlt,
  faBars,
  faChevronLeft,
  faBell,
  faEllipsisV,
  faChevronDown,
  faChevronRight,
  faTimes,
  faArrowRight,
  faSearch,
  faFilter,
  faTimes,
  faEdit,
  faTrash,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faPhone,
  faMapMarkerAlt,
  faClock,
  faEye,
  faUserPlus,
  faFileExport,
  faExclamationCircle
} from '@fortawesome/free-solid-svg-icons';

// Import des icônes de marques (réseaux sociaux)
import { 
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faInstagram
} from '@fortawesome/free-brands-svg-icons';

// Ajouter les icônes à la bibliothèque
library.add(
  // Icônes solid
  faHome,
  faUser,
  faCog,
  faBuilding,
  faFileContract,
  faCreditCard,
  faUsers,
  faUserTie,
  faUserShield,
  faUserTag,
  faReceipt,
  faChartBar,
  faChartLine,
  faChartPie,
  faTools,
  faCalendarCheck,
  faEnvelope,
  faPercentage,
  faFolder,
  faPlusCircle,
  faMoneyBillWave,
  faSignOutAlt,
  faBars,
  faChevronLeft,
  faBell,
  faEllipsisV,
  faChevronDown,
  faChevronRight,
  faArrowRight,
  faSearch,
  faFilter,
  faTimes,
  faEdit,
  faTrash,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  // Nouvelles icônes solid
  faPhone,
  faMapMarkerAlt,
  faClock,
  faEye,
  faUserPlus,
  faFileExport,
  faExclamationCircle,
  // Icônes de marques
  faGithub,
  faLinkedin,
  faTwitter,
  faFacebook,
  faInstagram
);

export { FontAwesomeIcon };